apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: xxx-account-xxx.dkr.ecr.us-east-1.amazonaws.com/api-server:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: SERVER_PORT
              value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: api-server-service
  labels:
    app: api-server-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:xxx-account-xxx:certificate/xxx-cert-xxx
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
  selector:
    app: api-server